# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Byte_Extra(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Byte_Extra()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsByte_Extra(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Byte_Extra
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Byte_Extra
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return -1

def Byte_ExtraStart(builder):
    builder.StartObject(1)

def Start(builder):
    Byte_ExtraStart(builder)

def Byte_ExtraAddValue(builder, value):
    builder.PrependInt8Slot(0, value, -1)

def AddValue(builder, value):
    Byte_ExtraAddValue(builder, value)

def Byte_ExtraEnd(builder):
    return builder.EndObject()

def End(builder):
    return Byte_ExtraEnd(builder)
