# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Model

import flatbuffers
from flatbuffers.compat import import_numpy

from .Vec3 import Vec3, Vec3T
from .Vec4 import Vec4, Vec4T

np = import_numpy()

class IKControl(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IKControl()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsIKControl(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # IKControl
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IKControl
    def IkName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # IKControl
    def IkChainStart(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # IKControl
    def IkChainEnd(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # IKControl
    def IkType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # IKControl
    def Res4(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # IKControl
    def IkPos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # IKControl
    def IkRot(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = o + self._tab.Pos
            obj = Vec4()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def IKControlStart(builder):
    builder.StartObject(7)

def Start(builder):
    IKControlStart(builder)

def IKControlAddIkName(builder, ikName):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(ikName), 0)

def AddIkName(builder, ikName):
    IKControlAddIkName(builder, ikName)

def IKControlAddIkChainStart(builder, ikChainStart):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(ikChainStart), 0)

def AddIkChainStart(builder, ikChainStart):
    IKControlAddIkChainStart(builder, ikChainStart)

def IKControlAddIkChainEnd(builder, ikChainEnd):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(ikChainEnd), 0)

def AddIkChainEnd(builder, ikChainEnd):
    IKControlAddIkChainEnd(builder, ikChainEnd)

def IKControlAddIkType(builder, ikType):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(ikType), 0)

def AddIkType(builder, ikType):
    IKControlAddIkType(builder, ikType)

def IKControlAddRes4(builder, res4):
    builder.PrependUint32Slot(4, res4, 0)

def AddRes4(builder, res4):
    IKControlAddRes4(builder, res4)

def IKControlAddIkPos(builder, ikPos):
    builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(ikPos), 0)

def AddIkPos(builder, ikPos):
    IKControlAddIkPos(builder, ikPos)

def IKControlAddIkRot(builder, ikRot):
    builder.PrependStructSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(ikRot), 0)

def AddIkRot(builder, ikRot):
    IKControlAddIkRot(builder, ikRot)

def IKControlEnd(builder):
    return builder.EndObject()

def End(builder):
    return IKControlEnd(builder)

try:
    from typing import Optional
except:
    pass

class IKControlT(object):

    # IKControlT
    def __init__(self):
        self.ikName = None  # type: str
        self.ikChainStart = None  # type: str
        self.ikChainEnd = None  # type: str
        self.ikType = None  # type: str
        self.res4 = 0  # type: int
        self.ikPos = None  # type: Optional[Vec3T]
        self.ikRot = None  # type: Optional[Vec4T]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        ikcontrol = IKControl()
        ikcontrol.Init(buf, pos)
        return cls.InitFromObj(ikcontrol)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, ikcontrol):
        x = IKControlT()
        x._UnPack(ikcontrol)
        return x

    # IKControlT
    def _UnPack(self, ikcontrol):
        if ikcontrol is None:
            return
        self.ikName = ikcontrol.IkName()
        self.ikChainStart = ikcontrol.IkChainStart()
        self.ikChainEnd = ikcontrol.IkChainEnd()
        self.ikType = ikcontrol.IkType()
        self.res4 = ikcontrol.Res4()
        if ikcontrol.IkPos() is not None:
            self.ikPos = Vec3T.InitFromObj(ikcontrol.IkPos())
        if ikcontrol.IkRot() is not None:
            self.ikRot = Vec4T.InitFromObj(ikcontrol.IkRot())

    # IKControlT
    def Pack(self, builder):
        if self.ikName is not None:
            ikName = builder.CreateString(self.ikName)
        if self.ikChainStart is not None:
            ikChainStart = builder.CreateString(self.ikChainStart)
        if self.ikChainEnd is not None:
            ikChainEnd = builder.CreateString(self.ikChainEnd)
        if self.ikType is not None:
            ikType = builder.CreateString(self.ikType)
        IKControlStart(builder)
        if self.ikName is not None:
            IKControlAddIkName(builder, ikName)
        if self.ikChainStart is not None:
            IKControlAddIkChainStart(builder, ikChainStart)
        if self.ikChainEnd is not None:
            IKControlAddIkChainEnd(builder, ikChainEnd)
        if self.ikType is not None:
            IKControlAddIkType(builder, ikType)
        IKControlAddRes4(builder, self.res4)
        if self.ikPos is not None:
            ikPos = self.ikPos.Pack(builder)
            IKControlAddIkPos(builder, ikPos)
        if self.ikRot is not None:
            ikRot = self.ikRot.Pack(builder)
            IKControlAddIkRot(builder, ikRot)
        ikcontrol = IKControlEnd(builder)
        return ikcontrol
