# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Int_Extra(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Int_Extra()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInt_Extra(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Int_Extra
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Int_Extra
    def Res0(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Int_Extra
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return -1

def Int_ExtraStart(builder):
    builder.StartObject(2)

def Start(builder):
    Int_ExtraStart(builder)

def Int_ExtraAddRes0(builder, res0):
    builder.PrependUint32Slot(0, res0, 0)

def AddRes0(builder, res0):
    Int_ExtraAddRes0(builder, res0)

def Int_ExtraAddValue(builder, value):
    builder.PrependInt32Slot(1, value, -1)

def AddValue(builder, value):
    Int_ExtraAddValue(builder, value)

def Int_ExtraEnd(builder):
    return builder.EndObject()

def End(builder):
    return Int_ExtraEnd(builder)
