# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Model

class MorphAttribute(object):
    NONE = 0
    POSITION = 1
    MIN_LIMIT = 2
    MAX_LIMIT = 3
    USER_ID = 10
