# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Model

import flatbuffers
from flatbuffers.compat import import_numpy

from .StringParameter import StringParameter

np = import_numpy()

class Shader(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Shader()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsShader(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Shader
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Shader
    def ShaderName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Shader
    def ShaderValues(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = StringParameter()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Shader
    def ShaderValuesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Shader
    def ShaderValuesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def ShaderStart(builder):
    builder.StartObject(2)

def Start(builder):
    ShaderStart(builder)

def ShaderAddShaderName(builder, shaderName):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(shaderName), 0)

def AddShaderName(builder, shaderName):
    ShaderAddShaderName(builder, shaderName)

def ShaderAddShaderValues(builder, shaderValues):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(shaderValues), 0)

def AddShaderValues(builder, shaderValues):
    ShaderAddShaderValues(builder, shaderValues)

def ShaderStartShaderValuesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartShaderValuesVector(builder, numElems: int) -> int:
    return ShaderStartShaderValuesVector(builder, numElems)

def ShaderEnd(builder):
    return builder.EndObject()

def End(builder):
    return ShaderEnd(builder)
