# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Sphere(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # Sphere
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Sphere
    def X(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Sphere
    def Y(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # Sphere
    def Z(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # Sphere
    def Radius(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))

def CreateSphere(builder, x, y, z, radius):
    builder.Prep(4, 16)
    builder.PrependFloat32(radius)
    builder.PrependFloat32(z)
    builder.PrependFloat32(y)
    builder.PrependFloat32(x)
    return builder.Offset()


class SphereT(object):

    # SphereT
    def __init__(self):
        self.x = 0.0  # type: float
        self.y = 0.0  # type: float
        self.z = 0.0  # type: float
        self.radius = 0.0  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        sphere = Sphere()
        sphere.Init(buf, pos)
        return cls.InitFromObj(sphere)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, sphere):
        x = SphereT()
        x._UnPack(sphere)
        return x

    # SphereT
    def _UnPack(self, sphere):
        if sphere is None:
            return
        self.x = sphere.X()
        self.y = sphere.Y()
        self.z = sphere.Z()
        self.radius = sphere.Radius()

    # SphereT
    def Pack(self, builder):
        return CreateSphere(builder, self.x, self.y, self.z, self.radius)
