# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class trskeleton(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = trskeleton()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAstrskeleton(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # trskeleton
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # trskeleton
    def Filename(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def trskeletonStart(builder):
    builder.StartObject(1)

def Start(builder):
    trskeletonStart(builder)

def trskeletonAddFilename(builder, filename):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(filename), 0)

def AddFilename(builder, filename):
    trskeletonAddFilename(builder, filename)

def trskeletonEnd(builder):
    return builder.EndObject()

def End(builder):
    return trskeletonEnd(builder)
