# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Model

class Type(object):
    NONE = 0
    RGBA_8_UNORM = 20
    RGBA_8_UNSIGNED = 22
    R_32_UINT = 36
    R_32_INT = 37
    RGBA_16_UNORM = 39
    RGBA_16_FLOAT = 43
    RG_32_FLOAT = 48
    RGB_32_FLOAT = 51
    RGBA_32_FLOAT = 54
