# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Model

import flatbuffers
from flatbuffers.compat import import_numpy

from .VertexAccessor import VertexAccessor, VertexAccessorT
from .VertexSize import VertexSize, VertexSizeT

np = import_numpy()

class VertexAccessors(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VertexAccessors()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVertexAccessors(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VertexAccessors
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VertexAccessors
    def Attrs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = VertexAccessor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VertexAccessors
    def AttrsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # VertexAccessors
    def AttrsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # VertexAccessors
    def Size(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = VertexSize()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VertexAccessors
    def SizeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # VertexAccessors
    def SizeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def VertexAccessorsStart(builder):
    builder.StartObject(2)

def Start(builder):
    VertexAccessorsStart(builder)

def VertexAccessorsAddAttrs(builder, attrs):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(attrs), 0)

def AddAttrs(builder, attrs):
    VertexAccessorsAddAttrs(builder, attrs)

def VertexAccessorsStartAttrsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartAttrsVector(builder, numElems):
    return VertexAccessorsStartAttrsVector(builder, numElems)

def VertexAccessorsAddSize(builder, size):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(size), 0)

def AddSize(builder, size):
    VertexAccessorsAddSize(builder, size)

def VertexAccessorsStartSizeVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSizeVector(builder, numElems):
    return VertexAccessorsStartSizeVector(builder, numElems)

def VertexAccessorsEnd(builder):
    return builder.EndObject()

def End(builder):
    return VertexAccessorsEnd(builder)

try:
    from typing import List
except:
    pass

class VertexAccessorsT(object):

    # VertexAccessorsT
    def __init__(self):
        self.attrs = None  # type: List[VertexAccessorT]
        self.size = None  # type: List[VertexSizeT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        vertexAccessors = VertexAccessors()
        vertexAccessors.Init(buf, pos)
        return cls.InitFromObj(vertexAccessors)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, vertexAccessors):
        x = VertexAccessorsT()
        x._UnPack(vertexAccessors)
        return x

    # VertexAccessorsT
    def _UnPack(self, vertexAccessors):
        if vertexAccessors is None:
            return
        if not vertexAccessors.AttrsIsNone():
            self.attrs = []
            for i in range(vertexAccessors.AttrsLength()):
                if vertexAccessors.Attrs(i) is None:
                    self.attrs.append(None)
                else:
                    vertexAccessor_ = VertexAccessorT.InitFromObj(vertexAccessors.Attrs(i))
                    self.attrs.append(vertexAccessor_)
        if not vertexAccessors.SizeIsNone():
            self.size = []
            for i in range(vertexAccessors.SizeLength()):
                if vertexAccessors.Size(i) is None:
                    self.size.append(None)
                else:
                    vertexSize_ = VertexSizeT.InitFromObj(vertexAccessors.Size(i))
                    self.size.append(vertexSize_)

    # VertexAccessorsT
    def Pack(self, builder):
        if self.attrs is not None:
            attrslist = []
            for i in range(len(self.attrs)):
                attrslist.append(self.attrs[i].Pack(builder))
            VertexAccessorsStartAttrsVector(builder, len(self.attrs))
            for i in reversed(range(len(self.attrs))):
                builder.PrependUOffsetTRelative(attrslist[i])
            attrs = builder.EndVector()
        if self.size is not None:
            sizelist = []
            for i in range(len(self.size)):
                sizelist.append(self.size[i].Pack(builder))
            VertexAccessorsStartSizeVector(builder, len(self.size))
            for i in reversed(range(len(self.size))):
                builder.PrependUOffsetTRelative(sizelist[i])
            size = builder.EndVector()
        VertexAccessorsStart(builder)
        if self.attrs is not None:
            VertexAccessorsAddAttrs(builder, attrs)
        if self.size is not None:
            VertexAccessorsAddSize(builder, size)
        vertexAccessors = VertexAccessorsEnd(builder)
        return vertexAccessors
