# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Model

class VertexAttribute(object):
    NONE = 0
    POSITION = 1
    NORMAL = 2
    TANGENT = 3
    BINORMAL = 4
    COLOR = 5
    TEXCOORD = 6
    BLEND_INDICES = 7
    BLEND_WEIGHTS = 8
    USER = 9
    USER_ID = 10
