# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Animation

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AnimationInfo(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AnimationInfo()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAnimationInfo(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AnimationInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AnimationInfo
    def Res0(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # AnimationInfo
    def Duration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # AnimationInfo
    def Framerate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def AnimationInfoStart(builder):
    builder.StartObject(3)

def Start(builder):
    AnimationInfoStart(builder)

def AnimationInfoAddRes0(builder, res0):
    builder.PrependUint32Slot(0, res0, 0)

def AddRes0(builder, res0):
    AnimationInfoAddRes0(builder, res0)

def AnimationInfoAddDuration(builder, duration):
    builder.PrependUint32Slot(1, duration, 0)

def AddDuration(builder, duration):
    AnimationInfoAddDuration(builder, duration)

def AnimationInfoAddFramerate(builder, framerate):
    builder.PrependUint32Slot(2, framerate, 0)

def AddFramerate(builder, framerate):
    AnimationInfoAddFramerate(builder, framerate)

def AnimationInfoEnd(builder):
    return builder.EndObject()

def End(builder):
    return AnimationInfoEnd(builder)
