# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Animation

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CamAnimation(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CamAnimation()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCamAnimation(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CamAnimation
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CamAnimation
    def CamName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CamAnimation
    def AnimInfo1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Titan.Animation.CameraAnim1 import CameraAnim1
            obj = CameraAnim1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CamAnimation
    def AnimInfo2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Titan.Animation.CameraAnim2 import CameraAnim2
            obj = CameraAnim2()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def CamAnimationStart(builder):
    builder.StartObject(3)

def Start(builder):
    CamAnimationStart(builder)

def CamAnimationAddCamName(builder, camName):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(camName), 0)

def AddCamName(builder, camName):
    CamAnimationAddCamName(builder, camName)

def CamAnimationAddAnimInfo1(builder, animInfo1):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(animInfo1), 0)

def AddAnimInfo1(builder, animInfo1):
    CamAnimationAddAnimInfo1(builder, animInfo1)

def CamAnimationAddAnimInfo2(builder, animInfo2):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(animInfo2), 0)

def AddAnimInfo2(builder, animInfo2):
    CamAnimationAddAnimInfo2(builder, animInfo2)

def CamAnimationEnd(builder):
    return builder.EndObject()

def End(builder):
    return CamAnimationEnd(builder)
