# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Animation

class FloatTrack(object):
    NONE = 0
    FixedFloatTrack = 1
    DynamicFloatTrack = 2
    Framed16FloatTrack = 3
    Framed8FloatTrack = 4
