# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Animation

class RotationTrack(object):
    NONE = 0
    FixedRotationTrack = 1
    DynamicRotationTrack = 2
    Framed16RotationTrack = 3
    Framed8RotationTrack = 4
