# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Animation

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class sVec3(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 6

    # sVec3
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # sVec3
    def X(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # sVec3
    def Y(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))
    # sVec3
    def Z(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreatesVec3(builder, x, y, z):
    builder.Prep(2, 6)
    builder.PrependUint16(z)
    builder.PrependUint16(y)
    builder.PrependUint16(x)
    return builder.Offset()
