# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Animation

class VectorTrack(object):
    NONE = 0
    FixedVectorTrack = 1
    DynamicVectorTrack = 2
    Framed16VectorTrack = 3
    Framed8VectorTrack = 4
