# automatically generated by the FlatBuffers compiler, do not modify

# namespace: TrinityScene

import flatbuffers
from flatbuffers.compat import import_numpy

from .Vec3f import Vec3f

np = import_numpy()

class SRT(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SRT()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSRT(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SRT
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SRT
    def Scale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = Vec3f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SRT
    def Rotation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = Vec3f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SRT
    def Translation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            obj = Vec3f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def SRTStart(builder):
    builder.StartObject(3)

def Start(builder):
    SRTStart(builder)

def SRTAddScale(builder, scale):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(scale), 0)

def AddScale(builder, scale):
    SRTAddScale(builder, scale)

def SRTAddRotation(builder, rotation):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(rotation), 0)

def AddRotation(builder, rotation):
    SRTAddRotation(builder, rotation)

def SRTAddTranslation(builder, translation):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(translation), 0)

def AddTranslation(builder, translation):
    SRTAddTranslation(builder, translation)

def SRTEnd(builder):
    return builder.EndObject()

def End(builder):
    return SRTEnd(builder)
